[package]
name = "stack-vm"
version = "0.1.0"
authors = ["James Harton <james@automat.nz>"]
license = "MIT"
description = "A generic, reusable, stack-based virtual machine."
documentation = "https://docs.rs/crate/stack-vm"
repository = "https://gitlab.com/huia-lang/stack-vm"
readme = "README.md"

[badges]
gitlab = { respository = "huia-lang/stack-vm" }

[dependencies]
